### ISSUE TITLE
Convert BTW crafting mechanisms to use a crafting manager

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#10]
https://github.com/BTW-Community/BTW-source/issues/42#issue-874973759
> The following methods of crafting items would be much smoother for addons if they used a crafting manager rather than individual hooks:
> 
> * Kiln
> * Saw
> * Piston packing
> * Secondary output crafting
> * Hopper item conversion

https://github.com/BTW-Community/BTW-source/issues/42#issuecomment-922688978
> A part of this should be moving sounds on crafting out of OnUsedInCrafting() and moved into the recipe definition, same as secondary results.
> 
> OnUsedInCrafting() will remain in case people want to make crafting do more complicated things.

https://github.com/BTW-Community/BTW-source/issues/42#issuecomment-923156682
> Kiln has been converted to crafting manager. Kiln overlay is currently hardcoded into RenderBlockSecondPass(). This should be changed to automatically detect kiln recipes. Ignoring for now until I convert all hardcoded methods into recipe definitions.

https://github.com/BTW-Community/BTW-source/issues/42

**Comment by ammoore00** [comment]
Several items have no need for their own class after moving packing functionality out of the item class. These classes should be removed and the items set to instances of the appropriate generic type.

**Comment by ammoore00** [comment]
Done for v1.1.0.

Sounds not moved out of OnUsedInCrafting() to simplify conditions on which to play sounds, instead of having to build a complicated system for it.
