### ISSUE TITLE
Incorrect bark returned by stone axe recipe for jungle logs

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#102]
AsterTM wrote on Discord:
> Hello, I'm playing on CE 1.1.7 and I think I found a bug: when crafting shafts with a stone axe and jungle logs, it gives me shafts, saw dust and oak barks instead of jungle barks.
> I tried with an iron axe and it gives me jungle barks though, so the problem is only for the stone axe
https://discord.com/channels/252863009590870017/252940065804648448/899232549186986016

**Comment by sanedsf** [comment]
Chisels produce the correct Bark item.

**Comment by ammoore00** [comment]
Fixed for next release
