### ISSUE TITLE
Half slabs block almost all creeper explosion damage

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#103]
Placing a half-slab between yourself and an exploding creeper negates almost all of the damage. Needs investigation for why it happens exactly and if it can be fixed.

**Comment by ammoore00** [comment]
Tall grass also blocks almost all creeper damage.

**Comment by ITLSupress** [comment]
Fixed as of CE 3.0 Snapshot 2.1, and During Transient Server.
