### ISSUE TITLE
Relogging removes endermen aggro

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#11]
https://github.com/BTW-Community/BTW-source/issues/44#issue-888706365
> Confirmed to work in singleplayer, unconfirmed for multiplayer (probably does not apply though)
> 
> Hypothesis is that aggro state is simply not stored in NBT data

https://github.com/BTW-Community/BTW-source/issues/44#issuecomment-875154730
> Turns out it will require much more work to fix than simply adding something to the NBT data. Aggro is stored in entityToAttack, which can't really be easily stored as when the save is loaded, that entity is regenerated from save data too.
> 
> Likely fix will be to store player UUID if it is attacking a player. On load, look within aggro range for a player with that UUID, and if none are found then aggro is lost.

https://github.com/BTW-Community/BTW-source/issues/44

**Comment by ammoore00** [comment]
Fixed for v1.1.0
