### ISSUE TITLE
Redstone and rails popping off platforms

### ISSUE THREAD

**Issue by Justin-Erwin** [BTW-Community/BTW-Public#113]
As of BTW CE 1.2.2, redstone and rails pop off platforms once moving. Fired up last FC release and redstone stays placed. 
Note: Automated item elevators still possible pre detector, though require some creativity.

**Comment by ammoore00** [comment]
Probably related to the new entity code introduced in 1.2. Will see what's happening there.

**Comment by ITLSupress** [comment]
![image](https://github.com/BTW-Community/BTW-Public/assets/38446419/99c3afe3-4059-4c96-a90a-5d2d10b387b1)
Not an issue as of CE 3.0 Snapshot 2.1.
