### ISSUE TITLE
Villager Trades

### ISSUE THREAD

**Issue by Justin-Erwin** [BTW-Community/BTW-Public#115]
Butcher:
Still asks for the old carrots
Runed Skull trade shows giving XP in the GUI at level four even though it doesn't. At Max level it shows no XP correctly.

Priest:
Infused skull and soul forge trades show as XP gain trades in the GUI at level four despite not not giving XP (at max this is corrected). Unfortunately, urns are the only trade that gain priest XP and it doesn't come around reliably. Maybe RNG gods hate me, but multiple times I did 10-15 consecutive trades without the urn trade available. Even though a couple of times it did pop up twice in a row, this was an extremely frustrating experience. More concurrently available trades would be nice on all of the villagers, but especially here where the Infused skull and soul forge are almost permanently taking up a spot and only urns can get him to the Infernal Enchanter level up trade.

Blacksmith:
Still a greedy asshole :) But less exhausting than the priest 

Librarian and Peasant were fine.

The old carrot and XP showing in the GUI are legit. Take the rest with a grain of salt. Other than the butcher becoming a gimp mask wearing cannibal, Villager trading is the least enjoyable part of the mod for me. It just feels very grindy. I'm glad you all are looking to make some changes.

**Comment by ammoore00** [comment]
Yep some villager rebalancing is definitely necessary. In the short term though I can fix stuff like the xp display being wrong (I know exactly the fix for that) and the carrot thing. I can also up the weight on the soul urn trade to make it more likely to appear (it being the only level 4 trade is something I want to address).

**Comment by ammoore00** [comment]
Aforementioned issues fixed for next release. Overall balance will be addressed in a later release.
