### ISSUE TITLE
Add alternate use keybinding

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#12]
This would allow for more complicated interactions like choosing the direction gearboxes face when placed, and allowing both placing and using buckets.

https://github.com/BTW-Community/BTW-source/issues/46

**Comment by ammoore00** [comment]
Moving the next version because of comprehensive controls gui changes necessary. All current space is occupied so more control options added would require a rewrite of the gui organization.

**Comment by ammoore00** [comment]
Completed by 1.3.0
