### ISSUE TITLE
Exiting the world when fishing rod is cast causes crash on reload

### ISSUE THREAD

**Issue by vgl266** [BTW-Community/BTW-Public#125]
A friend of mine got his save corrupted this way.
In CE v 1.0 this bug didn't exist, so it got broken somewhere after that version.

**Comment by ammoore00** [comment]
Not a corruption, just a missing mapping. The world will be fine once the mapping is added, will get a fix in.

**Comment by ammoore00** [comment]
Ended up being entirely different from what I thought, and potentially even a vanilla issue. Regardless, fixed for next release.

As a temporary fix for your friend to be able to play in their world again, open the world in MCEdit, and there will be a red box where the fish hook is. Select that area and in the menu on the left delete all entities in the selection, and the world should load fine.

**Comment by vgl266** [comment]
Thank you.
