### ISSUE TITLE
sprint / crouch / special button Disconnects clients from a server in CE1.3

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#134]
activating or de-activating any of these buttons while simultaneously moving disconnects the player from a server. Singleplayer works fine. 

Error that gets thrown: `java.io.IOException: Bad packet id 181` where id number keeps changing on different client boots in dev environment.

**Comment by Hirachosan** [comment]
disabling `this.sendQueue.addToSendQueue(new Packet19EntityAction(this, actionState));` stops the crash from happening (and stops special movement things from being sent to the server) so it's definitely this packet that's causing the issue

**Comment by Hirachosan** [comment]
found the error! things were changed to write int, but still tried to read a byte in packet19!

**Comment by ammoore00** [comment]
Fixed for next release
