### ISSUE TITLE
Grass color issue with smooth lighting off

### ISSUE THREAD

**Issue by ricardasnv** [BTW-Community/BTW-Public#140]
See attached pictures. The top surface of grass and leaf blocks turns gray when smooth lighting is off, but works fine with minimum/maximum. Happens only with CE 1.3.0 and above.
![Screenshot_2021-12-14_20-08-07](https://user-images.githubusercontent.com/16519359/146056137-4118b817-a179-4c4d-b979-efacda25eb99.png)
![Screenshot_2021-12-14_20-08-41](https://user-images.githubusercontent.com/16519359/146056142-dbf48bd2-2f73-4d1a-b68f-5a35b46785bb.png)

**Comment by ammoore00** [comment]
Fixed for 1.3.2
