### ISSUE TITLE
Scattered features not spawning

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#151]
Scattered features may not be properly generating according to this forum post: http://www.sargunster.com/btwforum/viewtopic.php?p=159307#p159307

Issue first occurred in 1.1.0 according to post.

Structures confirmed generating in BTA worlds so if bug is confirmed, investigate differences between vanilla and BTA generation?

**Comment by Hirachosan** [comment]
I was writing it off to bad RNG, but I only saw those little shrines and villages spawn in deserts as well. Checking Amidst it seems there should have been a couple.

**Comment by ammoore00** [comment]
Fixed for next release.
