### ISSUE TITLE
Recipes not working in certain saves

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#158]
In this save provided by DRiggZ, gearbox and hopper recipes do not work for some bizarre reason. No indication yet as to why this would be, given that recipe information is not stored with save files.

https://www.dropbox.com/s/moege43iswxe9jt/my%20messed%20up%20world.zip?dl=0

**Comment by Hirachosan** [comment]
Its caused by sawing woodtypes other than oak into gears

**Comment by ammoore00** [comment]
Fixed by #162
