### ISSUE TITLE
Increase Speed of Lowest-Tech Harvesting

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#170]
I would do it myself if I wasn't completely incompetent and overwhelmed by the process of making addons.  I tried downloading MCP, looking around in the code for what values to change and just generally trying to wrap my head around the workflow, and I realize that I am out of my depth.  I just think the early game should move faster, without necessarily adding anything or taking anything away.  All the addons I see that address the early game slog do so by adding complexity, and I'm not interested in that if it means more bugs, compatibility issues, and an order of magnitude more balance issues.  Even if what you choose seems like a negligible percentage of reduction, it would still help and be appreciated.  Honestly, if we could just do more in a given day and not have to put staplers on our mouse buttons, that would be great.

**Comment by ammoore00** [comment]
Potentially something that can be looked at for some of the alternative difficulty modes we've discussed. Not something I want to touch to much for the default experience, but not something I'm opposed to doing for alternative modes when we get around to implementing that kind of thing.

**Comment by AbbyRead** [comment]
By then I might be better equipped to deliver something along those lines if I'm able to modify SMEGMA to that.  No worries.  I wrote this when I was still butthurt and down on myself and my inabilities.  We'll cross that bridge when it comes.  👍

**Comment by ammoore00** [comment]
Implemented for upcoming "relaxed" difficulty mode
