### ISSUE TITLE
Rebalance costs on a few egregious trades

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#18]
> **@ammoore00** commented [on Jul 9](https://github.com/BTW-Community/BTW-source/issues/55#issue-940273209)
> The costs of some villager trades seem far too high compared to other prices. These should probably be brought in line with the rest of them.

> **@ammoore00** commented [on Sep 14](https://github.com/BTW-Community/BTW-source/issues/55#issuecomment-918703433)
> Some villager trades have been tweaked. Notable ones include bat wings and feathers. Leaving this issue up as another pass is definitely needed.

> **@Hirachosan** commented [on Sep 18](https://github.com/BTW-Community/BTW-source/issues/55#issuecomment-922107675)
> Mystery meat should probably be rebalanced to give more emeralds.
> 
> About bat wings: they are perfectly farmable, I noticed you said they were hard to get multiple times, but a lot of things are if you don't build for it.

> **@ammoore00** commented [on Sep 18](https://github.com/BTW-Community/BTW-source/issues/55#issuecomment-922137787)
> Even with building farms, 14-16 seems high to me. I changed it to 8-12. Still requires a farm, just a little bit lower.
> 
> As for mystery meat, the butcher was asking for 2-4 for 1 emerald. Right now I've changed it to 2-3, but that can be tweaked more if necessary.

https://github.com/BTW-Community/BTW-source/issues/55

**Comment by ammoore00** [comment]
Closing this for now as I feel the changes in 1.1.0 already are good enough for a first pass. I want to do a more comprehensive balance pass but I will open that as its own issue.
