### ISSUE TITLE
Ladder While Knitting

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#181]
Single Player
BTW-CE-1.3.6-client
BetterTerrainAddon-2.0.6-client
Quieter MillStone-client

Seems a little unexpected to be able to go up ladders just as fast with (by nature of knitting) both of your hands already occupied.  I realize this is a bit knit picky.  😏

![Ladder while Knitting](https://user-images.githubusercontent.com/77890127/154825791-bbd7a909-dbb9-492c-9d8d-1de6162f752f.gif)

**Comment by ammoore00** [comment]
Implemented for next release.
