### ISSUE TITLE
Make stumps harder to destroy by way of nearby creeper explosions

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#182]
I just think it makes stump removers kinda pointless.  Especially since they cost two bait items to make when early game, that's a precious resource.

**Comment by vgl266** [comment]
I agree with Hirachosan on this one. Using creepers to destroy stump is tedious enough for stump removers to become useful.

**Comment by ammoore00** [comment]
Yeah personally I think it's fine as is as well
