### ISSUE TITLE
Wolves aggro'd by group aggression do not reflect their aggression state

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#186]
As shown by this gif of one of my miserable and pathetic deaths, when they come to the aid of their comrades, they just seem happy as pie to be there.  Like they're about to give you a great big hug.

https://media.giphy.com/media/TGHY9F16SgeEqTK1Ya/giphy-downsized-large.gif

**BTW Version:** 1.3.6
**Multiplayer:** No.
**Issue:** It's hard to tell sometimes if they like me or want me dead.  Such is life.  *sigh*
**Steps to Reproduce:** Beat up a puppy next to some puppies.  I call all dogs puppies.
**Addons:** Just BTA in this recording

**Comment by ammoore00** [comment]
Editing the title of this to be more reflective of the issue

**Comment by vgl266** [comment]
Solved, will PR as soon as I determine just how much tradeoff do we want between code duplication and not messing with base classes.

**Comment by vgl266** [comment]
I found that the behavior can be added by removing overridden method FCEntityWolf.setAttackTarget(), which bypasses the vanilla wolf behavior (which correctly sets wolf to angry if it has been assigned to attack a player), but why this override exist in the first place? Any ideas?

**Comment by ammoore00** [comment]
Was fixed in 2.0.0
