### ISSUE TITLE
Allow "Peaceful" option or cheat

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#187]
Even if it's only available in creative mode, it would really help for testing/debugging purposes to not have mobs spawning in to wreck my shit if I put ANYTHING other than wood down on a superflat.

**Comment by ammoore00** [comment]
> /gamerule doMobSpawning false 

That will do what you want for testing purposes.

**Comment by AbbyRead** [comment]
Oooo!  Thanks!
