### ISSUE TITLE
Add to Debug screen: last block harvested from in however many seconds/milliseconds

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#188]
This is particularly something that would benefit SMEGMA's documentation, but I don't know if anyone else would use it.  I'm sure if I knew what was going on with the code with a lot more confidence, I could just calculate it outside of the game, but that's the rub; I don't.  It would make me very happy though if it's an easy thing to add.

**Comment by ammoore00** [comment]
Can you clarify what you actually want from this, and what you would use it for? I don't understand the request.

**Comment by AbbyRead** [comment]
I want to be able to test the differences between tool speeds on various blocks.  That way I can actually give info about the changes I make in a way that's meaningful to players.  If it's too much trouble, that's okay.  Just wanted to run it by you in case it's a quick thing to add or in case you might find a use for it too.

**Comment by ammoore00** [comment]
Definitely not a quick thing to add. If you want to find the exact time for mining then I'd check the vmc wiki for the equation, it should still be correct except for BTW removing instant mining.
