### ISSUE TITLE
Stop animal eating animation when spooked

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#193]
Animals eating grass still appear to be trying to eat grass while running away if you hit them during their eating animation.

**Comment by ammoore00** [comment]
I'll look into it. Depends on how much effort it is. If it's something super easy then I'll take care of it, but otherwise it's such a minor thing with very little consequence that it's not worth it if it isn't a super quick fix.

**Comment by PlasmaFox256** [comment]
Fixed and tested with blood and sweat.
The issue was graze counter not resetting to 0 on flee. I had this working within 5 minutes but unfortunately realised too late that fleeTick wasn't account for clientside. 
I blame FC >:(

**Comment by ammoore00** [comment]
Fixed for 2.0.2. Thanks PlasmaFox!
