### ISSUE TITLE
Make fishing nibble sound effect emanate from the player, client-side

### ISSUE THREAD

**Issue by AbbyRead** [BTW-Community/BTW-Public#197]
When fishing from a distance, it's often difficult or impossible to tell by ear if something is ready to be reeled in.  It makes sense from a player perspective to have more feedback in this already half-baked game mechanic.

**Comment by ammoore00** [comment]
Because of some weirdness this would cause in multiplayer I don't think it would work super well to do it as stated. However, I can certainly increase the volume of the fish bobber. Honestly fishing as a whole could do with a pass anyway.

**Comment by ammoore00** [comment]
Done for 1.3.9
