### ISSUE TITLE
Silverfish are useless in the End

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#2]
Silverfish had a nerf to preserve old stone builds in the end that was never undone leaving them non-existent in the end.

BTW-Community/BTW-Source#4

**Comment by ammoore00** [comment]
More information on the current system and issues can be found here: http://www.sargunster.com/btwforum/viewtopic.php?f=14&t=9743

**Comment by ammoore00** [comment]
Done for next release
