### ISSUE TITLE
Small change to mob drops

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#200]
Currently when you kill mob it instantly drops its loot and the its body gets thrown off to the side disappearing shortly. I have always felt weird about this so i think we should make the loot appear right when the actual corpse vanishes with those smoke particles, dropping the loot items in that exact spot where the corpse fell.

**Comment by ammoore00** [comment]
I fail to see what this would actually accomplish. There's basically 0 gameplay justification for the effort invested, which would be very non-trivial, and in fact could mess with mob traps by potentially putting their drops in walls.

**Comment by PlasmaFox256** [comment]
Fair enough, its only a minor detail.
