### ISSUE TITLE
Clean up custom entity spawn packets to be handled inside entity class instead of FCBetterThanWolves

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#21]
Spawn packets are weirdly handled in a very non-OOP way in ClientCustomPacketReceived right now in a very long method with tons of conditionals. This should be refactored to be less complex and more compartmentalized.

Related issue is that vanilla entity packets are handled similarly. Should probably be refactored at the same time.

While this functionality is super janky, client packet intercepts do currently allow a method for addons to modify.

https://github.com/BTW-Community/BTW-source/issues/61

**Comment by ammoore00** [comment]
Refactored custom packets as a whole to use custom handlers to help with this and similar issues. Entity spawn packets still should be moved into their own classes but that will require further work.
