### ISSUE TITLE
Piston packing recipes ignore input metadata

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#211]
` FCCraftingManagerPistonPacking.FCCraftingManagerPistonPackingRecipe getValidRecipeFromItemList(List<EntityItem> itemList) ` makes a map of block Ids of the entities  linked to stacksize. there's no metadata check here so it matches the first recipe with the same input ID

**Comment by ammoore00** [comment]
Fixed for next release

**Comment by Hirachosan** [comment]
Fixed for real now!
