### ISSUE TITLE
Give each log and stump their own respective wood type top texture

### ISSUE THREAD

**Issue by socklessthing** [BTW-Community/BTW-Public#214]
This feature was added with Deco and I think it should be in the base game.

**Comment by PlasmaFox256** [comment]
The top textures in deco seem a bit off, I would suggest getting the ones from 1.7.10.

**Comment by ammoore00** [comment]
The textures in deco *are* the ones from 1.7 (I technically pulled them from 1.13 but it's the same texture).

The stump textures were created by subtracting the oak log top from the stump top, and then adding that to the other log types.

**Comment by ammoore00** [comment]
Also I realize I never acknowledged this, but yeah I'm totally fine with that. Should probably come also with deco's wood type specific chewed logs.

**Comment by Hirachosan** [comment]
I'm all for this as well, as well as the chewed log part since that follows naturally

**Comment by PlasmaFox256** [comment]
> The textures in deco _are_ the ones from 1.7 (I technically pulled them from 1.13 but it's the same texture).
> 
> The stump textures were created by subtracting the oak log top from the stump top, and then adding that to the other log types.

I checked in 1.7.10 and yes, the logs look identical to the ones in deco. I must be used to having oak top for every single log haha

**Comment by ammoore00** [comment]
Complete for 2.0.0
