### ISSUE TITLE
multi break stump instead of unintuitive 1minute breaking time

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#220]
I think it would be more intuitive if we add multiple stages of crafting the stump into a workbench, normally if something takes this long to break it is an indication that you're doing something wrong

**Comment by ammoore00** [comment]
Definitely makes sense, I'm down for that

**Comment by PlasmaFox256** [comment]
I had the same thought recently. My idea was to make the carving happen on right click, but multiple stages sound way better.

**Comment by ammoore00** [comment]
Completed by https://github.com/BTW-Community/BTW-source/pull/181
