### ISSUE TITLE
Allow fishing in river

### ISSUE THREAD

**Issue by guanyuxin** [BTW-Community/BTW-Public#230]
In current code EntityFishHook, fishing checks 5 * 5 * 3(2?) block around fish hook, any block that is other then water makes fishing effortless. This is originly for prevent puddle fisshing, but it also make fishing in a river or swamp fails. these biome has water that is not deep enough but oftern quite large, disallow fishing for that is quite unrealistic

Maybe should checking wider but thiner area around the hook make this better

**Comment by ammoore00** [comment]
Yeah currently planning on looking at some tweaks for fishing. Low priority but it is on our radar :)

**Comment by ammoore00** [comment]
2.0.2 changed fishing check pattern to be a diamond instead of a square to help with this
