### ISSUE TITLE
spider from spawner does not drop string

### ISSUE THREAD

**Issue by guanyuxin** [BTW-Community/BTW-Public#233]
I run into a dungon with spider spawner near my base. thought I was lucky and start build tunnel to trap and killing spiders. but only lost few good axes before I realize they just dont drop string

I search for code FCEntitySpider.java and found this:
```
+    @Override
+    public void SpawnerInitCreature()
+    {
+    	// does not call super or initCreature() to override spider jokey generation
+    
+        m_iTimeToNextWeb = m_iTimeBetweenWebs;    	
+    }
```
this may intend to stop spider from spawner eject web immediately after they spawn, make the spider spawner a death trap for player near by. but this also make spider cannot drop string on death because system think the spider has already lost it's web.

Mayby it's better for SpawnerInitCreature to use a separate cooldown timer, prevent spider to shoot web a few seconds after they spawn, and make m_iTimeToNextWeb just for web cooldown and hasweb check

**Comment by ammoore00** [comment]
Working as intended. Spiders from spawners are not supposed to spawn with webs at all to prevent easy infinite string. Spiders do not have a cooldown timer, they only ever get one web.
