### ISSUE TITLE
some things are broken

### ISSUE THREAD

**Issue by No-steve** [BTW-Community/BTW-Public#235]
I play BTW-CE v1.4.1 with some addons in MultiMC5.
![mod](https://user-images.githubusercontent.com/105639186/192141763-35e9fcf2-beb1-4b69-9eac-095c6d05d78d.png)
Then, I ran into some problems.
1.
![image](https://user-images.githubusercontent.com/105639186/192141885-31c59085-39e1-48ca-8ef8-74a23dbc0aa7.png)
These items have no name or no texture.

2.
![image](https://user-images.githubusercontent.com/105639186/192142134-aefdda3a-35ea-4fbd-a23a-3367b7933d3b.png)
I have placed a smooth stone and a red stone torch like this, but the torch doesn't rotate.
I use other blocks it works fine.

3.
![image](https://user-images.githubusercontent.com/105639186/192142582-0302ea1a-88d0-4ba7-bf1c-13f6415fe03b.png)
I opened my inventory, but the tips don't disappear.
 
I use some addons, but I don't know what's causing these problems, so I created an issue here.

**Comment by ammoore00** [comment]
Issues should be one topic per post. Also please verify if issues are due to addons before posting here. If you're not sure, feel free to ask on discord :)

1 is deco, not BTW
2 might be an actual issue with BTW, feel free to repost that one
3 is presumably a bug caused by Achievements Core

**Comment by Hirachosan** [comment]
2 works fine without those outdated and unmixable addon list. addon issue not CE
