### ISSUE TITLE
Sfx Update

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#243]
Looking into the future, if CE gets ported to newer Minecraft versions - it should hopefully become easier to work with sounds and music. I would love if we could get the updated block and item sounds that Mojang slowly created over the updates, including new ambient soundtracks.  In 1.5.2, the music system is global, which feels weird at times. You get overworld music in the nether, which doesn't fit the dimension and most blocks have the same stone breaking sounds.

The Sfx update wouldn't _just_ include the new sounds from Mojang but also some new sound effects potentially. I strongly believe small details in sound really adds to the gameplay experience as you get immersed in the world of Minecraft. We could create new sound effects and play around with it, give some blocks more variety and love.

So, obviously this is a very low priority addition, but I wanted to make sure I get it out there and at least look forward to it.
👍

**Comment by ammoore00** [comment]
Yup already planning on doing stuff with sounds once we have the ability to.
