### ISSUE TITLE
Missing Sounds

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#248]
CE2.0.0 no addons
Some minor sound effects seem to be missing in this version. For example: animals eating food, mining ore from stone; sometimes axle and millstone sounds don't play but that might be unrelated due to the game reaching sound channel limit.

**Comment by ammoore00** [comment]
Yep, known issue. Working on a fix :)

**Comment by ammoore00** [comment]
Unfortunately seeming to be a more complicated issue than I had hoped. Everything is working with the effect handlers and the effect is being appropriately delegated. Particle effects are spawned properly, it is only sounds which are not playing.

**Comment by ammoore00** [comment]
Fixed for next release
