### ISSUE TITLE
Add sprint key

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#27]
> I want to do this properly which will involve some changes to options gui and game settings to allow convenient control changes.

https://github.com/BTW-Community/BTW-source/issues/79

**Comment by ammoore00** [comment]
Moving the next version because of comprehensive controls gui changes necessary. All current space is occupied so more control options added would require a rewrite of the gui organization.

**Comment by ammoore00** [comment]
Completed by 1.3.2
