### ISSUE TITLE
Monsters burn in rain

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#293]
Skeletons and zombies catch fire even while it's raining; causing repetitive sound effects and visual flickering.
It's a 1 line fix, just waiting for issue review.

**Comment by ammoore00** [comment]
Sure, seems like a good change to me

**Comment by PlasmaFox256** [comment]
Although it's cloudy while raining, do we still want monsters to catch on fire under non-opaque blocks? Because they currently do that, not in thunderstorms though.

**Comment by PlasmaFox256** [comment]
Fixed for CE2.0.2

**Comment by Hirachosan** [comment]
So uh. using !worldObj.isRaining() would make them not burn up in desserts I suppose? and about the thunderstorms and rain. that's all about light level. thunderstorms are dark enough for them not to burn up while rain still has enough light to do so when they aren't being sizzled by the rain drops. all in all this change seems to make more bugs than to fix anything that needed fixing

**Comment by ammoore00** [comment]
I fixed most of those already when i merged the code in. They still don't burn while under glass in the rain but that's an easy fix.

**Comment by PlasmaFox256** [comment]
> 

I assumed that monsters shouldn't catch on fire when it's raining, even in deserts because it becomes cloudy.

**Comment by ammoore00** [comment]
That would be a change in behavior, which is different than what is presented in this ticket, and would require further discussion. Personally though, i don't have an issue with current behavior.
