### ISSUE TITLE
sapling can break any block that have gravity in it

### ISSUE THREAD

**Issue by AstroC0re** [BTW-Community/BTW-Public#303]
planting sapling before blocks reach the ground like dirt can break it 
instantly

**Comment by PlasmaFox256** [comment]
This also goes for slabs and some other non full blocks. We probably want them all to get crushed instead of the falling block stack to drop.

**Comment by ammoore00** [comment]
Fixed for next release.

Other non full blocks with this behavior like slabs are a far more complicated affair, and any such discussion should have its own issue (although I do not plan to address that at this time)
