### ISSUE TITLE
Wolves aggro'd by non-player entities become aggressive to the player as well.

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/BTW-Public#308]
In 4.03, the wolf did not turn red and attack the player even when attacked by someone other than the player.
In CE, the eyes turn red and attack the player, but is this an intentional adjustment?

**Comment by ammoore00** [comment]
Will look into it. Likely due to the fix in CE a while ago so that pack aggro'd wolves would no longer instantly lose aggro.

Also editing the title to be more descriptive.
