### ISSUE TITLE
Automated mortar

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#31]
>  **@ammoore00** commented [on Sep 21](https://github.com/BTW-Community/BTW-source/issues/85#issue-1000582341)
>  As per title. Mortar not being automateable is a pain in the ass for building.

>  **@Hirachosan** commented [on Sep 21](https://github.com/BTW-Community/BTW-source/issues/85#issuecomment-923383451)
> I propose (regular?)dispensers facing a block that is mortarable can inject mortar into that block. this would make it possible to fully automate a process using block dispensers and regular dispenser and some form of a timer

https://github.com/BTW-Community/BTW-source/issues/85

**Comment by ammoore00** [comment]
Done for v1.1.0

**Comment by Hirachosan** [comment]
Curious as to what you chose here! Care to elaborate?

**Comment by ammoore00** [comment]
I just did exactly what you proposed :) A couple other people have also suggested the same thing and I thought it was a good way to go.

**Comment by Hirachosan** [comment]
so the regular dispenser and facing directly towards the loose block? :)

**Comment by ammoore00** [comment]
Yep :)
