### ISSUE TITLE
Cobweb and sand

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/BTW-Public#310]
When sand or gravel is placed on a slab, it turns into powder, but when a cobweb floats in the air, it remains sand.

**Comment by ammoore00** [comment]
That's due to cobwebs being non-solid. Don't have any plans to fix as it's super minor and doesn't really impact the game.

**Comment by upperman3** [comment]
👍

**Comment by LannyRipple** [comment]
Closing based on Dawn's comment that this is a won't-fix.
