### ISSUE TITLE
wolves don't fight

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/BTW-Public#312]
When the player attacks zombies, etc., the wolves also become hostile to the zombies, but when the player throws snowballs, they are not hostile, but is this an intentional adjustment?

**Comment by ammoore00** [comment]
Snowballs don't deal damage, which is why that is happening. Not strictly intentional, but also wolf companion AI isn't really something I'm interested in adjusting as it'd be more work than it's worth. Wolves fighting for you is more of a remnant of vanilla than an intentional feature kept in BTW.
