### ISSUE TITLE
Webs disappear on half slabs and stairs

### ISSUE THREAD

**Issue by LannyRipple** [BTW-Community/BTW-Public#321]
Came across this in the forums and didn't see it recorded here.
Forum link: https://sargunster.com/btwforum/viewtopic.php?t=10193

Summary - When a web would normally disappear because it cannot be placed instead drop a non-placeable item that can be refined into string.

**Comment by ammoore00** [comment]
Good call putting this over here as well

**Comment by Hirachosan** [comment]
was fixed with the webbing drop in 2.1
