### ISSUE TITLE
Strata-based Stone Tools

### ISSUE THREAD

**Issue by Blacklands** [BTW-Community/BTW-Public#327]
Since a while, each strata (stratum?) is (from what it seems like ingame) a separate block ID and drops its own separate stone blocks.
(Whereas before, this was just done via metadata I think, and when broken one would always get the "regular" first-strata stone.)

Following this approach, I'm wondering if there should also be two more separate versions of each stone tool, for the other two deeper strata. Right now, crafting tools with those stones just give you the regular stone tools.

I think this could be interesting because it would give you a little extra reward for being able to break those stones (iron pickaxe for second and diamond/steel for third strata) and for carrying them around at all (cluttering your inventory more because they don't stack with the first-strata stone anymore).
The stone tools would have more durability (maybe double for second-strata tools and triple for third-strata ones?). Maybe they would also be a bit faster (still way slower than iron, but noticeably faster than regular first-strata stone ones).
They would not have any additional capabilities - functionally they would still be stone tools, just with better "stats".

**Comment by ammoore00** [comment]
Why would you need slightly better stone tools once you already have access to better materials to mine those stratas though? Seems redundant to me tbh.

**Comment by Blacklands** [comment]
Just because I got enough iron for one or two iron tools doesn't mean I can use them for everything now?
We're using stone tools all the time when we can. We only use our precious iron tools when we have to (iron pickaxe for second strata mining, iron axe for cutting wood or breaking planks-based blocks, iron shovels when we're really pressed on time to dig a shelter or when we don't want dirt blocks to come loose while digging).

I could also turn your question around and ask: Why are we having the other strata stones as separate blocks at all right now if we can't even make slightly improved tools out of them? Seems pretty redundant. They just clutter up storage. I guess they're slightly more durable in terms of explosion resistance? And they might matter on anarchy multiplayer servers?

Well, anyway, it was just a suggestion. I guess I might make an add-on for this if there's no other usage for those stone types added. Right now we just use them for road building because it's also kind of ugly to mix them with the regular stone in building (which we have so much more of).

**Comment by PlasmaFox256** [comment]
Tools in BTW have distinct tiers and unlock "eras" of the game. By adding extra tools tiers that don't contribute to gameplay other than a different texture and minimal stat increases would only clutter the game and create inconsistency. Why not add birch, oak, jungle or spruce tools? - there is simply no need as they will function the same
Personally I'm not a fan of strata cobblestones and all other variants since they severely clutter the game purely for decoration purposes.

**Comment by Blacklands** [comment]
There's already tool tiers in the game that add nothing new to the functionality of a tool and simply have higher stats, though.
What does a diamond shovel have over an iron shovel? What do the soulforged steel tools have over iron/diamond?

Honestly, I don't even want this _this_ much. I just want _something_ to do with all this strata stone that isn't irrelevant for gameplay.  Because right now these separate stone types just existing feels bad.

 I would much rather have the old state back where all the strata gave you the same type of stone.
 Caving is already a very dangerous activity, plus you're on a timer (until you have nether torches). Now with all those strata type stones and cobblestones cluttering your inventory even more (it's already pretty bad imo how your inventory gets cluttered in Better Than Wolves since "piles" and single stones were added), you have to stop and do inventory management (if only to throw out all the second/third strata stuff) even more. And for what - for a little more decoration options super far down the line?
 
 Alternatively, how about you get first-strata stone drops from second/third strata stone unless you're using a soulforged steel tool or diamond pickaxe?
 Then you can still have your extra decoration options later on, but it's at least not making the early game caving worse.

**Comment by PlasmaFox256** [comment]
That's what I'm saying bro

**Comment by Hirachosan** [comment]
lets just make all logs drop oak wood then? Just because you don't see a point in variety doesn't mean there isn't or wont be expanded upon. The added clutter is very minor compared to what stone already does since AAH and managing inventory space it is an actual part of BTW balance. you break a different block you get a different item. That said. there was supposed to be a recipe to just let you mix the stones to get the worst quality one. But that one needed a little more thought while the balance of the current change could be tested. This change wasn't made for "a little more decoration options" it has been made for consistency

**Comment by Blacklands** [comment]
Well, if more is planned for this, then that's great.
As far as I'm aware, there is no public roadmap right now for future versions. So all we "outsiders" can comment on is what's currently in the game.

And how is my suggestion here not about consistency? Why is breaking different blocks and getting different types fine, but then crafting tools with that gives you the same tool all the time? Either it's for gameplay reasons and not consistency, or it's currently inconsistent.

Since wood types were mentioned: I assume that more stuff from the `Deco` AddOn will eventually get rolled into the base game, and we'll get all the wood-based blocks (like doors, fences, trapdoors, and the like) for the different wood types, too? Which would also make sense for consistency reasons (and be nice for decoration, of course).

**Comment by LannyRipple** [comment]
> I don't know how you're not seeing my point _at all_. Maybe your playstyle is totally different, and you do _way_ more caving and get _way_ more iron and never use stone tools again after you got your first iron tools. We're still using stone tools all the time, we only use the iron tools when we need to.

She saw your point.  She doesn't agree with it.  If this is important to you then with modding getting easier for BTW you can just create a mod that gives you those stone tools.  What's that you say?  You don't know how to make mods and you want Dawn, who gives her work freely to the community and in her spare time, to do all the work?  I suspect that's the point that she's not seeing.
