### ISSUE TITLE
Make Witches able to open Doors

### ISSUE THREAD

**Issue by Blacklands** [BTW-Community/BTW-Public#328]
Right now, witches are not smart enough to be able to open doors. I find that kind of weird, since they should be as smart as villagers at least, right?

If they could open doors (and fence gates, and trapdoors), that might provide some little extra challenge when building a base in/next to a swamp. I just had a witch stand on the other side of a door, staring at me, unable to get in. I feel like they should be able to do that.

Maybe that would also offer a new use for iron doors (outside of maybe anarchy-based multiplayer servers or the like)? Since FlowerChild removed zombies being able to bash down doors (which made sense to remove with the new early game of course), those have felt kind of useless.

**Comment by ammoore00** [comment]
Tbh I'm not really sure what this would really add. FC removed zombies breaking down doors because it just led players to not use doors in the early game, or block the doors with blocks. Plus witches are enough of a threat that that could legitimately kill a player, which would feel unfair I feel.

**Comment by Blacklands** [comment]
They're definitely a threat, yeah, as long as you can't deal with their poison potions yet. 
I guess to me right now doors feel a little _too_ safe. There's nothing in the game that can deal with a door.
Zombies are abundant, so they would break your doors all the time, which would just make you not use them probably, yeah. Witches are a lot more rare, even in swamps. It would be one way to not feel totally safe in your base in/next to a swamp.

**Comment by ammoore00** [comment]
> There's nothing in the game that can deal with a door

There are absolutely things in the game which break down doors :) Just ones the player doesn't encounter as regularly.

I think living in a swamp already has enough challenges. The rare witch can be a threat as I mentioned, and slimes are no joke either. Having a bit of safety as a reward for getting an iron axe seems entirely fair to me.
