### ISSUE TITLE
Bed(roll)s allow skipping gloomy nights

### ISSUE THREAD

**Issue by Blacklands** [BTW-Community/BTW-Public#329]
It seems that the progression of the "gloom" effect (being in darkness) is not sped up while sleeping in a bed(roll). At least not in multiplayer (I haven't tested in SP).
This means that gloomy nights (especially the ones where it's new moon) can be skipped safely without a light source by just sleeping through them. The night will be over before the player starts taking damage from the darkness.

This is probably not intended, is it?

Possible solutions:

- Speed up the "gloom" effect, like everything else is also sped up
- Make players unable to go to sleep/cancel ongoing sleep when they are under the "gloom" effect

---

Also, a question: Is the speed-up a fixed amount? (And if so, how much?) Or does it go as fast as the system can run all the game code calculations? The wiki doesn't specify this right now.

**Comment by Hirachosan** [comment]
The intention was for it to be sped up, as sleeping simply makes time(and thus all updates) go as fast as the server/pc can handle.. Can't think of how this is in any way possible though, probably needs investigation

**Comment by ammoore00** [comment]
Yeah this is unlikely to be an issue with gloom specifically, that's just likely a manifestation of a deeper issue. If it does actually end up being an issue with gloom specifically, then it could make sense to just not allow the player to sleep in gloom, but I find it unlikely that that is the only issue.

The game attempts to make time go up to 50x faster, but that's basically impossible and so realistically it ends up being as fast as the computer can handle it.

**Comment by Blacklands** [comment]
Thanks for the clarification on speed.
I think the most the VPS I am playing on with my buddies right now can do is about 10x speedup. That's enough to get through a whole night before getting to "terror" in the gloom progression.

I haven't tested it yet, but I could imagine that this might happen with other status effects, too. Would be interesting to see if the poison status gets sped up or not.
