### ISSUE TITLE
Added the ability for wheat to grow under light blocks.but there is no sign of growing

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/BTW-Public#332]
Placed a light block directly above the wheat and passed power through it
but it doesn't grow at all
Wheat originally grows slowly, so it may be a misunderstanding, but does it really grow faster?
Or will it be placed on the second tier instead of directly above the wheat? (Because the height of the fully grown wheat is the second row)

**Comment by Hirachosan** [comment]
The last thing is correct, it needs to be 2 spaces between the dirt/pot and lightblock

However, it does not grow faster. This is only for hemp. It makes hemp grow during the night. 

For wheat it just makes it so you dont need sunlight. No speed increase

**Comment by upperman3** [comment]
I see . thank you
