### ISSUE TITLE
 I can't use the blacksmith's brick furnace

### ISSUE THREAD

**Issue by upperman3** [BTW-Community/BTW-Public#333]
Unable to use the brick furnace installed in the blacksmith in the village 3000 away from the spawn point.
Weird looking and sometimes weird orientation

Deco4.01
CE2.04

**Comment by Hirachosan** [comment]
do you have a seed and location?

**Comment by upperman3** [comment]
Every seed I've experienced has had bugs. Also interesting are the viewpoints in the desert and jungle temples.

**Comment by ammoore00** [comment]
Closing in favor of #374 since that one has more useful information in it

**Comment by upperman3** [comment]
I understand. I won't report anything else on CE.
