### ISSUE TITLE
Sinew - Early game string replacement

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#334]
String is a bit too random to acquire, so there needs to be a way to get string that is slower, but guaranteed. After discussing in the community, we landed on meat -> string. Even that is not really costly enough though, so we decided to make it require time too.

One piece of meat turns into a knitting/weaving type job where you process the meat to get sinew, a replacement for string in recipes.

Alternatively it could just result in string

**Comment by LannyRipple** [comment]
#cd-dev sinew discussion starts https://discord.com/channels/252863009590870017/832731036864741438/1150800577635295232
