### ISSUE TITLE
[1.6.4] Village generation startPiece is null, causing a crash

### ISSUE THREAD

**Issue by TheWinABagel** [BTW-Community/BTW-Public#342]
[crash-2023-07-08_18.30.36-server.txt](https://github.com/BTW-Community/BTW-Public/files/12009964/crash-2023-07-08_18.30.36-server.txt)
Generated a fresh world, moved around a bit then this happened, causing the world to be effectively locked

**Comment by ammoore00** [comment]
Relevant is the editneeded note in ComponentVillage - BTW stuff references the start piece object, but this doesn't seem to be used in BTW
