### ISSUE TITLE
[1.6.4] Crash when rendering block break FX

### ISSUE THREAD

**Issue by TheWinABagel** [BTW-Community/BTW-Public#343]
[crash-2023-07-08_17.09.40-client.txt](https://github.com/BTW-Community/BTW-Public/files/12009979/crash-2023-07-08_17.09.40-client.txt)
I don't know what block caused this, but I couldn't replicate it consistently, and I sadly wasn't thinking about it and deleted the world save :(

**Comment by ammoore00** [comment]
Fixed as part of removal of createEntityOfType() hooks
