### ISSUE TITLE
[1.6.4] Soul urns + dynamite crashes when thrown

### ISSUE THREAD

**Issue by TheWinABagel** [BTW-Community/BTW-Public#345]
It's fine when fired from a dispenser though.
[crash-2023-07-14_23.53.26-server.txt](https://github.com/BTW-Community/BTW-Public/files/12060618/crash-2023-07-14_23.53.26-server.txt)

**Comment by ammoore00** [comment]
Cause was introduction of EntityLivingBase in 1.6. This has been fixed as a part of the removal of the old createEntityOfType() hooks
