### ISSUE TITLE
Villagers do not allways have their permanent trades available

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#356]
As per title, using a permanent villager trade makes them randomly pick a new trade, this is not always the permanent trade one

**Comment by Hirachosan** [comment]
They also show a + sign indicating that they give villager experience while they do not contribute to that

**Comment by ammoore00** [comment]
Fixed mandatory trades not refreshing. Opening the GUI issue as a new ticket.

**Comment by ammoore00** [comment]
New Ticket created as #361
