### ISSUE TITLE
Pickblock on a burning campfire gives a burning campfire

### ISSUE THREAD

**Issue by Joel-Paul** [BTW-Community/BTW-Public#357]
Picking a burning campfire then placing it places a campfire that is burning then instantly changes to smouldering
![campfirebug](https://github.com/BTW-Community/BTW-Public/assets/37064691/2b7e1b6a-4471-4538-b5db-eb45a6ebfd9d)
(sorry for the gif quality :P)

**Comment by ammoore00** [comment]
Fixed for next release
