### ISSUE TITLE
Harvesting mushroom blocks with a BD gives the Old Mushroom block (CE 2.0.4)

### ISSUE THREAD

**Issue by Battosay52** [BTW-Community/BTW-Public#362]
Harvesting mushroom blocks with a BD gives the Old Mushroom block for all 3 mushroom block types (stem, brown and red cap)

**Comment by ammoore00** [comment]
It actually was returning the correct blocks, just the new blocks were still using the old names and did not have their own names. Fixed for next release (although I would like to do a more proper overhaul of mushroom cap blocks in the future to make them more usable as they are kinda janky right now)
