### ISSUE TITLE
Villagers wont update their available trades properly

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#372]
Possibly multiple causes, current findings:

- villagers with perma trades dont refresh the right amount of trades, seemingly not taking into account they need extra trades to compensate the taken slot by perma trades
- villagers wont update their trades unless a perma is used, often getting stuck on even less than their level is supposed to have. ( say a level 4 butcher only keeps 3 trades, untill you trade the skull-> wither skull, then it resets to 4 again. Trading a random trade puts it back to three max
- villagers seem to constantly try to add a new trade, popping sound, purple whirling, without anything happening

**Comment by ammoore00** [comment]
Fixed for next release

**Comment by ammoore00** [comment]
Also fixed a longstanding bug with normal trades rarely not refreshing to the correct number as a part of this fix
