### ISSUE TITLE
Missing sounds, small visual bugs

### ISSUE THREAD

**Issue by Progrstick** [BTW-Community/BTW-Public#385]
Skulls, wooden, and iron doors don't have placement sounds.
Item frames have no sound when placed or broken.
Villagers don't make sounds when attacked.

+Zombie Pigmans are randomly burning in the overworld.
+Cave and jungle spiders have too big a shadow.

**Comment by ammoore00** [comment]
That is all vanilla behavior from 1.5.2. Sounds will be getting a full pass to bring the mod closer to vanilla parity with the 1.6 update, and the shadow thing is something I can look at, but none of those are technically bugs with the mod.

Also, please keep posts to a single issue.
