### ISSUE TITLE
Melons are too powerful

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#41]
Melons are far too rewarding in their food output. Solution is probably to reduce melons from 1/3 to 1/6 shank. This preserves their use for chickens but makes them way less of an uber food for the player.

**Comment by SimonMeskens** [comment]
Feedback thread: http://www.sargunster.com/btwforum/viewtopic.php?f=14&t=10112

**Comment by ammoore00** [comment]
Melons may no longer be sliced by hand and now require a saw. For now that will solve some of the power of melons, awaiting a future rework of melons as a whole
