### ISSUE TITLE
Spam clicking makes a fire plough and bow drill faster

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#425]
BTW Version: 2.1.4
Multiplayer (yes/no): no
Issue (be as specific as possible): Spam clicking makes a fire plough and bow drill faster
Steps to Reproduce (even if obvious): Spam click with a primitive fire starter
Addons (with versions): n/a
Crash Log (if there was a crash): n/a

**Comment by Polar-Onyx** [comment]
For added context:
Issue appears to be with FCItemFireStarter.java.patch onItemUse() triggering every time right click is pressed and affects both the bow drill and fire plough
This method is faster than holding rightclick even as low as 6cps with faster clicking being marginally faster at the cost of increased hunger use. Normally it takes ~30 seconds to start a campfire with the fire plough but 6cps gives ~18 seconds and higher cps can go as low as ~12 seconds

**Comment by Hirachosan** [comment]
was fixed in 3.0
