### ISSUE TITLE
Pistons not viable block for packing

### ISSUE THREAD

**Issue by prof-ion** [BTW-Community/BTW-Public#432]
Please do not post addon bugs, this is for bugs in BTW CE only.

Please use the following template for bug reports.

BTW Version: 2.1.4
Multiplayer (yes/no): no
Issue (be as specific as possible): When testing using a double extending piston for packing, discovered that pushing an unextended piston doesn't pack items into blocks. 
Steps to Reproduce (even if obvious): use sticky piston to push another piston attempting to pack. 
Addons (with versions): latest BTA, Dynamic lights, craft guide, dynamic items speed up. Not yet tested in vanilla BTW. But I suspect the issue carries over. 
Crash Log (if there was a crash): NA

**Comment by Hirachosan** [comment]
fixed for next release
