### ISSUE TITLE
Horses rearing when hurt makes them too easy to kill

### ISSUE THREAD

**Issue by ammoore00** [BTW-Community/BTW-Public#454]
Rearing behavior upon taking damage should be removed so they are able to swiftly kick the player as intended instead of sitting there taking hits

**Comment by prof-ion** [comment]
Maybe, and perhaps I am just evil. But horses jump fairly high still right? Could make them also randomly jump while running. Not sure if that would make this better or worse. But I had a fun mental image of it when I read this.

**Comment by ammoore00** [comment]
Horses jumping while being ridden is actually independent of their standard jumping, and also imo would look too silly while panicked
