### ISSUE TITLE
Missing and flashing textures

### ISSUE THREAD

**Issue by VexianEmpire** [BTW-Community/BTW-Public#459]
Please do not post addon bugs, this is for bugs in BTW CE only.

Please use the following template for bug reports.

BTW Version: 2.1.4
Multiplayer (yes/no): no
Issue (be as specific as possible): All textures seem to be broken, only happens once entering world, chunks become invisible, clouds flashing in and out of existence
Steps to Reproduce (even if obvious):
1. Opening game, everything seems fine
2. Enter a world
3. Upon loading in, textures are missing
4. If you exit world and go back to title screen, textures are still weird
5. Only resets when you close the game and reopen
Addons (with versions): 
Crash Log (if there was a crash):

note: i am using multimc version
this is the first time i tried this mod and idk what to do

Version:
LWJGL 2 | 2.9.4-nightly-20150209
Minecraft | 1.5.2
Cursed Fabric Loader BTW 1.1.0 | 1.1.0-1.5.2 (Custom)
BTW-CE-2.1.4 (jar mod) | (Custom)
![image](https://github.com/BTW-Community/BTW-Public/assets/64798986/49d891d9-9372-4750-98e7-127096fa27b9)
![image](https://github.com/BTW-Community/BTW-Public/assets/64798986/2ecb6802-4804-437a-8a14-b560c73677aa)
![image](https://github.com/BTW-Community/BTW-Public/assets/64798986/e1aa6fb1-0b53-4cdf-ad68-a52ef4e1db78)

**Comment by Battosay52** [comment]
This is a known issue.
You need to use Neodymium :
https://github.com/BTW-Community/Neodymium/releases/latest
See the #faq on the BTW discord or ask over there for help

**Comment by VexianEmpire** [comment]
ok thanks i will try with that now (also sorry i didnt find this as an already issue)

**Comment by VexianEmpire** [comment]
this issue is probably resolved but i have a different issue that i will post now
