### ISSUE TITLE
Rename Vanilla Hardcore to Permadeath

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#463]
Now that the community seems to have landed on "permadeath" as the name for vanilla hardcore vs BTW hardcore (which old-timers call hardcore spawn), I think we need to rewrite the text in the config (and in-game?) referring to it. This will also handily get rid of the whole hardcore confusion.

The wording should be written so that permadeath is seen as a disabling of features, rather than adding permadeath (the current warning is pretty good and probably just needs minor rewording).

I'm willing to do the PR if that's easier? Would I need to PR twice to two branches? (1.6 and 1.5)?

**Comment by PlasmaFox256** [comment]
Maybe BTW shouldn't even have such config option, to discourage hardcore/permadeath altogether. People can manually delete worlds anyway, and streamers can just overlay a "Hardcore" tag or whatever. 

With hardcore mode removed, we can use hardcore hearts to indicate whether HardCoreSpawn is active or not. So for example on new world creation, HCS is enabled, when you die it would be disabled for about 12 minutes and if a player is in range of a respawn beacon, HCS would be disabled again with hearts changing appearance depending on the state of HSC.

**Comment by SimonMeskens** [comment]
The hardcore hearts are really important for streamers, and players, we can't change those. People expect streamers to show the hardcore hearts and expect to have them when they make screenshots for their friends. It's silly, but it is what it is. It's an important marketing tool.

Dawn mentioned wanting to get rid of the permadeath option altogether... I'm on the fence. The previous change to move permadeath into the config was already quite contentious, and I think removing it altogether might result in community backlash.

**Comment by SimonMeskens** [comment]
To clarify: I was massively in favor of moving the option to config, but I'm unsure about removing it altogether. I wasn't or am not against either change.

**Comment by PlasmaFox256** [comment]
Yeah, fair enough. In that case I would suggest reverting the hardcore hearts to be exclusive to hardcore mode (for clarity purposes).

**Comment by SimonMeskens** [comment]
I think you misunderstand, BTW is hardcore by default, that is what Hardcore Spawn is. FC has always explained it that way too: he considered HCS to be a better way to do hardcore than permadeath. The problem was that streamers playing regular BTW with HCS would not receive the hardcore hearts, prompting them to turn on permadeath, and therefore encourage viewers to also play permadeath.

It is 100% intended that the default BTW hearts are hardcore hearts, that will not be changing. They are an indication of hardcoreness, not of permadeathness.

**Comment by PlasmaFox256** [comment]
First of all, streamers don't turn on hardcore just for the hardcore hearts, they do it for the permadeath challenge (which the hearts indicate). If we plan to keep the "Hardcore" challenge that came from vanilla MC, we need to make it clear what's going on to avoid confusion or said backlash. Otherwise, what's the point of keeping a traditional vanilla challenge if you aren't gonna make it clear and recognisable.

**Comment by cocona20xx** [comment]
If permadeath is going to stay in BTW:CE, it should honestly stay as a config option even with the name change, and if it isn't, the code to handle permadeath worlds should be kept—an addon should be able to make a few small edits to add it back. Imo getting rid of it entirely (but making it easy to reenable via a plugin) is the best option, but that'll likely be rather contentious.

**Comment by SimonMeskens** [comment]
> First of all, streamers don't turn on hardcore just for the hardcore hearts, they do it for the permadeath challenge (which the hearts indicate). If we plan to keep the "Hardcore" challenge that came from vanilla MC, we need to make it clear what's going on to avoid confusion or said backlash. Otherwise, what's the point of keeping a traditional vanilla challenge if you aren't gonna make it distinct from BTW features and recognisable.

Multiple streamers have literally told us that they turn on hardcore just for the hearts and that it multiplies the engagement they get. I'm sure they also do it for the challenge and enjoy the challenge, but they have told us the PRIMARY reason is often for engagement. Those hearts just make videos go burrr.


> If permadeath is going to stay in BTW:CE, it should honestly stay as a config option even with the name change, and if it isn't, the code to handle permadeath worlds should be kept—an addon should be able to make a few small edits to add it back. Imo getting rid of it entirely (but making it easy to reenable via a plugin) is the best option, but that'll likely be rather contentious.

This is the way I'm leaning I think? I would definitely keep the machinery, and if it's removed from the config, I kinda want there to be an addon to re-enable it from day one. Not sure.

**Comment by Hirachosan** [comment]
as of 3.0. Permadeath has been removed entirely as an option to remove any semblance of support to play the mod this way. We strongly encourage people to play out the same world. if they chose otherwise they can opt to delete worlds, but the mod itself will not facilitate it as it counters core game design
