### ISSUE TITLE
MC-19 fixed in 14w08a "Having FOV over 100 and sleeping in bed will cause you to look inside your head"

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/BTW-Public#465]
BTW Version: CE 2.1.4
Multiplayer (yes/no): no
Issue (be as specific as possible): When setting the FOV slider above 100, and sleeping in a bed, you will see the inside of your head. As posted in [MC-19](https://bugs.mojang.com/browse/MC-19?jql=project%20%3D%20MC%20AND%20text%20~%20%22inside%20of%20head%20bed%22) which was fixed in 14w08a (1.7.6)
Steps to Reproduce (even if obvious): Turn FOV to 100 or higher then sleep in a bed.
Addons (with versions): none

This seems like a more crucial bug to fix because of sleeping mechanics it is necessary to see ovens and other surroundings when sleeping with accelerated time. Might be easier to limit fov to 100 when sleeping than to port the 1.7.6 fix.

**Comment by ITLSupress** [comment]
Happening to all FOV levels above 90 for me on CE 3.0 Snapshot 2.1.

**Comment by Hirachosan** [comment]
fixed for next release
