### ISSUE TITLE
Jungle spiders attack without provocation in relaxed mode

### ISSUE THREAD

**Issue by DynamicWorlds** [BTW-Community/BTW-Public#467]
BTW Version: CE 2.1.4
Multiplayer (yes/no): no
Issue (be as specific as possible): Jungle spiders attacked me after they found me after spawning in one of the Better Biomes tropical biomes.  Was just gathering materials.  Remade world and made sure was in relaxed mode and was attacked again.
Steps to Reproduce (even if obvious): go to a biome where they spawn and find one in relaxed survival mode
Addons (with versions):  Better Biomes addon v: 3.2.2
                                     Better Terrain Addon v: 3.2.2
                                     Craft Guide v: 3.0.1
                                     Deco Addon v: 4.1.2
                                     DynamicLight Mod v: 1.1.0
Crash Log (if there was a crash): N/A: no crash

**Comment by ammoore00** [comment]
My suspicion, along with #466, is that your world is not actually on relaxed difficulty. Better terrain used to have a bug where it did not respect the choice made at world creation, I believed that to be fixed but it is possible it is not.

Can you double check through the options screen with the world open, or by running the /difficulty command without arguments, to verify your current difficulty?

**Comment by DynamicWorlds** [comment]
Confirmed that the worlds (plural) were on standard difficulty via the options menu despite making double sure they were on relaxed on creation.  I had double checked before (I thought) by checking if other relaxed features were active, (specifically jump placement of blocks, and mistakenly thought that block breaking wasn't startling animals) and assumed that since some relaxed world features were active that they all should be.

Just did another test and yes:
1-set relaxed on world creation
2-set the other better terrain/biomes settings to what I was using before
3-went back to confirm that it was still on relaxed
4-created the new world
5-immediately checked options and found difficulty on standard in options
6-tested jump placing of blocks (which worked on standard
7-tested animal reaction to placing blocks (panicked on standard, but didn't on relaxed)

Current workaround is sufficient for my needs, but I'm willing to do more testing on my end if it would help.

**Comment by Arminias** [comment]
This was a known bug in BTA 3.2.1, fixed in 3.2.2. Can you test again without any addons installed?
Else this post is better suited for the respective addon's issue page.

**Comment by DynamicWorlds** [comment]
Sorry for the delayed response, was busy with some stuff irl.
I did do some more testing and found a jungle biome without any addons.  The difficulty was not switching to hardcore survival and jungle spiders didn't attack.

That does mean that Arminias is correct that it should be in the respective addon's issue page.  IDK if there's a way to move this over there or if I should just create a new issue there.  (new to this stuff)
