### ISSUE TITLE
Fish hook does not check water radius as intended

### ISSUE THREAD

**Issue by PlasmaFox256** [BTW-Community/BTW-Public#469]
BTW Version:
CE2.1.4
Multiplayer (yes/no):
no
Issue (be as specific as possible): 
isBodyOfWaterValidForFishing() did not correctly check the water source block radius (intended to be 2 block radius as a sphere around the fish hook).
Supposed to be this:
![image](https://github.com/BTW-Community/BTW-Public/assets/84658200/dbc28323-a3a0-4654-9b57-ac325b3e4ea4)
Instead, the current method can only check for the initial 5x3x5 area for water source blocks but doesn't properly account for the radius inside that area.
Steps to Reproduce (even if obvious):
Try fishing in a suitable body of water.
Addons (with versions): 
N.A.
Crash Log (if there was a crash):
N.A.

**Comment by PlasmaFox256** [comment]
I made a pull request to BTW-main-merged with my bug solution.

**Comment by PhysisRocks** [comment]
>finds the bug
>fixes it
>refuses to elaborate further
>leaves

absolute gigachad.

**Comment by ammoore00** [comment]
Fixed for next release.
