### ISSUE TITLE
Wolf's One Shot

### ISSUE THREAD

**Issue by morbis-archives** [BTW-Community/BTW-Public#472]
BTW Version: 2.1.4
Multiplayer (yes/no): Yes
Issue (be as specific as possible): Wolfs are oneshoting
Steps to Reproduce (even if obvious): Sometimes if you are mining wood a wolf with likely teleport/run fast as speed of light and kill you
Addons (with versions): Craft Guide, Dynamic light, Map Marker, Progresive Item SpeedUp Addon.
Crash Log (if there was a crash):

**Comment by Arminias** [comment]
Tick-debt, related to speedup either via the Progressive Item Speedup Addon or sleeping.
Already fixed for next release.
