### ISSUE TITLE
[3.0] BD doesn't apply silk touch to brick oven

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#474]
![image](https://github.com/BTW-Community/BTW-Public/assets/4284735/771f4945-d4ab-4e31-beaa-34dfa85afb52)

**Comment by ITLSupress** [comment]
![image](https://github.com/BTW-Community/BTW-Public/assets/38446419/988c8cec-7523-4646-b10e-e0e6bca2aa1e)
They place them completely broken as well.

**Comment by Hirachosan** [comment]
actually a 2.1.4 bug. @ITLSupress dont post info on unrelated issues please

fixed awaiting PR
