### ISSUE TITLE
Items dont like to exist in hand

### ISSUE THREAD

**Issue by Zencorn1234** [BTW-Community/BTW-Public#480]
Please do not post addon bugs, this is for bugs in BTW CE only.

Please use the following template for bug reports.

BTW Version: 2.1.4
Multiplayer (yes/no): Yes
Issue (be as specific as possible): Every time I hold an item in my hand my hotbar turns all white and every texture starts to go crazy or turn to a single shade
Steps to Reproduce (even if obvious): Hold item in hand
Addons (with versions): No
Crash Log (if there was a crash): No crashes
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/1dd5f57a-dafa-4cd2-874f-13396b931ca5)
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/6b34b950-36b9-47c8-83ea-7e5fa3d9686c)
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/8c0a9f28-7449-4c16-81f9-ca0f276b585f)

**Comment by Zencorn1234** [comment]
wait crap i attached 2 of the same photo, I hope this is easier to tell
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/0e897d5b-0f7e-442a-b59a-cc5b38d35257)
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/b2a147c6-37fa-4c30-a577-053bf35a9dd8)
![image](https://github.com/BTW-Community/BTW-Public/assets/96205918/70252f4a-fa74-43eb-9d54-385664b6592b)

**Comment by Arminias** [comment]
Yes, Neodymium addon fixes this. Will also be fixed in 3.0 in BTW itself, it's an old vanilla bug with Intel GPUs.
