### ISSUE TITLE
[3.0] Tile entities that are immediately powered after being pushed lose their metadata

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#481]
![image](https://github.com/BTW-Community/BTW-Public/assets/4284735/d02d0506-fc09-41fb-a803-e85f0adbfaab)

**Comment by Hirachosan** [comment]
only seems to happen with vanilla dispeners

**Comment by ITLSupress** [comment]
Can confirm it still happens in Snapshot 2.1 and it does not work with Hoppers, only dispensers.

**Comment by Hirachosan** [comment]
fixed for next release
