### ISSUE TITLE
While holding control, you can't use the shift key for another task

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#483]
This makes the default keybinding for alternative use not work while sneaking

**Comment by Hirachosan** [comment]
This issue has been in 1.5.2 as well. depending on what button you press first you get different results

it's actually the other way around. pressing shift while already pressing control(alternative use key) makes it forget you're holding control

pressing control while holding shift works as intended

**Comment by ITLSupress** [comment]
Still an issue on Snapshot 2.1 CE 3.0, most noticeable scenario is trying to put tools into the ground using CTRL -> SHIFT vs SHIFT -> CTRL.
