### ISSUE TITLE
[3.0] End portal frame crash upon use with eye of ender

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/BTW-Public#488]
BTW Version: 3.0
Multiplayer: no
Issue (be as specific as possible):
Steps to Reproduce (even if obvious): right click an end portal frame with a eye of ender
Crash Log (if there was a crash):[crash-2024-02-13_14.33.32-server.txt](https://github.com/BTW-Community/BTW-Public/files/14271854/crash-2024-02-13_14.33.32-server.txt)

seems to be referring to this line: https://github.com/BTW-Community/BTW-source/blob/47dab971f586d2d96af61558b1a50570ccf98272/src/btw/java/net/minecraft/src/Direction.java#L19

**Comment by Arminias** [comment]
Fixed
