### ISSUE TITLE
[3.0] Rainbow wolf bug (make them a feature Dawn, geez)

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#494]
![image](https://github.com/BTW-Community/BTW-Public/assets/4284735/c0057ff0-75ba-4ccc-ba6b-8b3a301d42ea)

**Comment by Polar-Onyx** [comment]
Affects Infused Skull as well feel free to make this into a new issue if preferred
![image](https://github.com/BTW-Community/BTW-Public/assets/72043633/b249d8ce-9cd7-48b3-8333-6a59a4d35d0c)
![infused_skull_eyes](https://github.com/BTW-Community/BTW-Public/assets/72043633/5136cc7e-e0ed-4f69-8970-7d9c0c835ec8)
