### ISSUE TITLE
[3.0] Blaze AI is broken

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#497]
Quoting Battosay: "blaze AI seems busted, they don't come after you when aggroed, they just hover in one place ?"

**Comment by Hirachosan** [comment]
Apparently entities that have isAIEnabled false get their base speed set to 0.1F in EntityLivingBase.applyEntityAttributes. 
have to override that. I'll check the other entities as well

**Comment by Arminias** [comment]
Seems weird. Would probably need a check against vanilla 1.6 source on both ends

**Comment by Hirachosan** [comment]
so uhh. i just launched a vanilla 1.6.4 and seems blazes are actually just bugged there. i think my fix is the actual fix
