### ISSUE TITLE
[3.0] Redstone can't be placed on chopping blocks anymore

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#503]
Per title

**Comment by Hirachosan** [comment]
caused by isNormalCube, but that method was added to prevent choppingblock./saw killed mobs from not dropping anything. 
suffocation should probably be decoupled from isNormalCube

**Comment by Hirachosan** [comment]
the specific issue of redstone being places should be fixed in zero's pr if I understood correctly. the point of decoupling suffocation damage still holds but is more involved than i thought. so maybe not worth it

**Comment by Hirachosan** [comment]
Wasn't fixed in Zero's PR. but now fixed for next release in https://github.com/BTW-Community/BTW-source/commit/53dd28c53d177fb430f12d518135c87f42578a31
