### ISSUE TITLE
[3.0] Broken translation strings for a number of blocks, findable with the keyword "tile"

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#506]
![image](https://github.com/BTW-Community/BTW-Public/assets/4284735/fdf45162-717c-4a4f-a0c5-c342c799089b)

**Comment by SimonMeskens** [comment]
There might be more with the keyword "null"

**Comment by Polar-Onyx** [comment]
it effects all the blocks in the screenshot not just the grass

**Comment by SimonMeskens** [comment]
Yup, that's what the title says
