### ISSUE TITLE
Empty Clause issue for Vanilla Installation

### ISSUE THREAD

**Issue by DeathManeYT-ModCode** [BTW-Community/BTW-Public#510]
BTW Version: BTW CE 2.1.4
Multiplayer (yes/no): No
Issue (be as specific as possible): Loading error
Steps to Reproduce (even if obvious): Booting the game with the mod.
Addons (with versions): None outside what comes with it.
Crash Log (if there was a crash):
![Fabric Loader 2_18_2024 8_39_21 PM](https://github.com/BTW-Community/BTW-Public/assets/121408915/7e62b5d2-1e7e-4d00-99d6-78f9270055db)
Image of the crash log as this was what it said. And no, I can't use other loading methods. MMC has it's own weird issue and other methods just don't even register the mod.

**Comment by SimonMeskens** [comment]
BTW CE is for Minecraft 1.5.2, there's a reference to 1.18.2 in your log

**Comment by SimonMeskens** [comment]
Follow the install guide here: https://wiki.btwce.com/index.php?title=Installation

**Comment by DeathManeYT-ModCode** [comment]
> Follow the install guide here: https://wiki.btwce.com/index.php?title=Installation

I followed the guide to a tee, the version even said I loaded up 1.5.2.

**Comment by DeathManeYT-ModCode** [comment]
> > Follow the install guide here: https://wiki.btwce.com/index.php?title=Installation
> 
> I followed the guide to a tee, the version even said I loaded up 1.5.2.

![Minecraft Launcher 2_18_2024 9_16_44 PM](https://github.com/BTW-Community/BTW-Public/assets/121408915/1ccd92b2-f865-4172-a87a-afb66d8f8e5a)

**Comment by SimonMeskens** [comment]
Post a full log, screenshots are basically useless to us

**Comment by DeathManeYT-ModCode** [comment]
The latest log is from 2023, and the MMC logs show that it boots, but don't
show the bizarre texture glitch that always happens when loading it,

The exit code for the vanilla launcher is always 1.

**Comment by SimonMeskens** [comment]
The texture glitch is solved easily by Neodymium for BTW. Join our Discord and we can help you figure out this issue, but it doesn't sound like it's a bug on our end.
