### ISSUE TITLE
[3.0] Dung beacon's poison effects are inverted

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/BTW-Public#513]
Issue: Dung beacons give players poison but it doesn't do damage unless they wear a full set of soulforge steel
Steps to Reproduce: Place a dung beacon and then put on a set of soulforge steel armor

**Comment by Hirachosan** [comment]
this works fine in dev. mapping issue

**Comment by Arminias** [comment]
Not a mapping issue, does not work in my dev env

**Comment by Hirachosan** [comment]
another one that was fixed in my branch,
