### ISSUE TITLE
[3.0] hellfire beacons don't ignite

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/BTW-Public#514]
Issue: Hellfire blocks are intended catch of fire when the beacon they are a part of is active but they do not.
Steps to Reproduce: Build a hellfire beacon

**Comment by Hirachosan** [comment]
Broken since Beacon rewrite. Simply forgot that that was a thing :) needs fire resist beacon to get its own BeaconEffect class that lits the hellfire onPowerOn to be similar to old BTW. or make it periiodically try to lit fire using onUpdate

**Comment by ITLSupress** [comment]
![image](https://github.com/BTW-Community/BTW-Public/assets/38446419/4cdfd85d-5782-4dea-9a59-a2e7fe1d7a88)
I don't think the beacon is firing at all based on what I'm seeing.

**Comment by Hirachosan** [comment]
fixed for next release
