### ISSUE TITLE
[3.0] Nether Growth Spores Don't damage the player

### ISSUE THREAD

**Issue by Polar-Onyx** [BTW-Community/BTW-Public#516]
Issue: As title no damage is done wearing soul forge armor or not on nether spores
Steps to Reproduce: place nether growth spore and wait for them to fully mature and walk on them in survival mode

**Comment by Hirachosan** [comment]
Dev works fine: another mapping issue

**Comment by Arminias** [comment]
Not a mapping issue, caused by non-updated instanceof EntityLiving check

**Comment by Hirachosan** [comment]
yep. apparently already fixed as a side effect of fixing clay being stepped on :D

**Comment by Hirachosan** [comment]
Fixed
