### ISSUE TITLE
[3.0] Dung beacon poisons you but doesn't affect till getting out of range with in the body

### ISSUE THREAD

**Issue by nicknewbie2k3** [BTW-Community/BTW-Public#519]
BTW Version: 3.0.0 snapshot 2
Multiplayer (yes/no): No
Issue (be as specific as possible): Dung beacon does give you the poison effect, but it doesn't affect you until you step out of the beacon range. Possibly re-applies beacon effects in such a way that the damage tick gets delayed,
Steps to Reproduce (even if obvious): 1. Make at least a tier 1 dung beacon. 2. Stepping in the beacon range to receive the poison effect. Stay inside the beacon range and notice the poison effect doesn't damage you. 3. Step out of the beacon range. The poison effect duration will go down and you receive poison damage.
Addons (with versions): None 
Crash Log (if there was a crash): None
![image](https://github.com/BTW-Community/BTW-Public/assets/116050319/a8cdf542-63ef-4442-8d4a-784ff2d06970)

**Comment by Hirachosan** [comment]
fixed
