### ISSUE TITLE
Applying dye colors things into the wrong color

### ISSUE THREAD

**Issue by Hirachosan** [BTW-Community/BTW-Public#520]
post from anarchX
- The Vase recipes gives the wrong color vases.
- The Hardened Clay hues on some blocks are off. (Look at screenshot. Cyan > Blue > Light Gray in that order.) 

![image](https://github.com/BTW-Community/BTW-Public/assets/81694306/69364385-3d31-4abf-84c3-2143ea44f30d)

![image](https://github.com/BTW-Community/BTW-Public/assets/81694306/a2d064bc-e5a9-4373-a790-c69893dbebaf)

**Comment by rytir2001** [comment]
The hardened clay just looks like this in vanilla 1.6.4, so I'm not sure if this should be considered a bug.

I fixed the first point of this issue and am waiting for the code review on the pull request. :)

**Comment by Hirachosan** [comment]
fixed vases for next release, clay blocks just look like that
