### ISSUE TITLE
Textures and chunks bug out, making the game nearly unplayable.

### ISSUE THREAD

**Issue by xtexecute** [BTW-Community/BTW-Public#531]
BTW Version: V2.1.4
Multiplayer: No
Issue: Chunks stop rendering when you break a block, the ui keeps glitching when you hold an item
Steps to Reproduce: Break a block and hold an item
Addons: None
![Ekran görüntüsü 2024-05-11 162348](https://github.com/BTW-Community/BTW-Public/assets/146252866/3f65cccc-d18d-443c-8437-9f30c668dac7)
![Ekran görüntüsü 2024-05-11 162546](https://github.com/BTW-Community/BTW-Public/assets/146252866/c70c0332-275a-4b56-9502-bdd31eaf78ea)
![Ekran görüntüsü 2024-05-11 162554](https://github.com/BTW-Community/BTW-Public/assets/146252866/3f4b3dc8-e378-4761-b945-3c0f68249549)

**Comment by Arminias** [comment]
Intel driver bug, present in all old vanilla Minecraft versions. For 2.1.4, install the Neodymium addon, for 3.0 there is an internal fix.

**Comment by xtexecute** [comment]
> Intel driver bug, present in all old vanilla Minecraft versions. For 2.1.4, install the Neodymium addon, for 3.0 there is an internal fix.

uhh
i don't know if i'm installig the right thing but it doesn't seem to be working.

**Comment by Arminias** [comment]
This is the one: https://github.com/BTW-Community/Neodymium/releases/tag/v0.2.1
Put the jar into your mods folder. Make sure you use Java 8. If that doesn't work, you can for further troubleshooting join our discord.
