### ISSUE TITLE
the game doesn't work

### ISSUE THREAD

**Issue by MioHazard** [BTW-Community/BTW-Public#532]
I just recently tried to play the mod, but as soon as I tried to start a world, it didn't work.
when I try opening a world to play, it gets stuck on the loading screen forever. I've tried joining different worlds, but it's the same issue every time over and over again, and I have no idea why.

**Comment by vb1dra** [comment]
what does consol log says?
is it has "10% 20% ... 95% 100% world created" or no?
is it clear btw, or with addons?
what version of btw?
can u play btw before, or its first time?
(im not an expert, its just a qustions)

**Comment by MioHazard** [comment]
1. it just keeps saying "loading world" (forever)
2. it's clear btw
3. it's my 1st time (& I rly RLY wanna play it)

**Comment by Arminias** [comment]
You could try running a newer version than that one. Also, are you typing in seeds?

**Comment by MioHazard** [comment]
I didn't type any seeds, but when I looked at the version list that was the latest version I found

**Comment by Arminias** [comment]
It is the oldest one you can find on this Github. For modern versions, here is the installation guide: https://wiki.btwce.com/index.php?title=Installation
