### ISSUE TITLE
Feature Request: Hardcore Fog

### ISSUE THREAD

**Issue by ikabod-kee** [BTW-Community/BTW-Public#544]
**The problem:**
Players with better computers will always have an advantage over players with worse computers because of render distances. Plus, you are able to manipulate mob spawning and other mechanics by changing render distance.

**The solution:**
1. Remove render distance option; make it always "Normal."
2. Have foggy days where fog slowly sets in around the player, without changing the render distance.
3. Make rain and thunder increase the amount of fog.

**Advantages:**
Added fog on certain days creates difficulty and atmosphere!
Players will have equal playing ground regardless of specs.

**Comment by Polar-Onyx** [comment]
> Plus, you are able to manipulate mob spawning and other mechanics by changing render distance.
False, there is no gameplay difference between tiny and far other than visual range all players will always simulate 14x14 chunks around them in BTW.

Also I have no idea why you would want to artificially limit the already tiny range old java gives you the real solution is optimize the game so even potato pcs can run far render distance like sodium
