### ISSUE TITLE
Death out of nowhere

### ISSUE THREAD

**Issue by Sushy270** [BTW-Community/BTW-Public#551]
Version:
2.1.4 CE

Multiplayer:
No
 
Difficulty:
Eelaxed
 
Issue:
Randomly dying and items disapearing instantly.

1. Hit by ghast with full tanned leather armor and full health (normaly a few hearts)
Death Message: Player was shot by skeleton
After returning only 2 mystery meat and some netherrack are left

2. 10 minutes after first incident: jumping down from 4 blocks high death occurs
An explosion sound can be heard
Death Message: Player died
After returning nothing destroyed(no explosion), only 2 mystery meat

Steps to Reproduce:
None, further information coming?

Addons:
Craft Guide V3.0.2

**Comment by ammoore00** [comment]
The first sounds like you got direct impacted by a ghast fireball, followed by being shot by a skeleton (regular skeletons can occasionally spawn in place if wither skeletons).

The second one sounds like you took fall damage while holding blasting oil.

None of the deaths are suspicious themselves, and I'd need more information to comment on anything about the items. I do not recall if blasting oil detonating inside your inventory destroys items or not, and it's possible stuff fell into fire for the ghast, but hard to say for sure.

**Comment by Sushy270** [comment]
Wow thank you very much that was a quick reply.
That definitely will be it. I've looked everywhere for an answer for this but couldnt find anything.
Its my first time playing and almost read through the hole wiki, but didnt have that in mind.

And blasting oil apparently destroys all the items in the inventory.
You can close or delete the issue. Thank you very much.

**Comment by ammoore00** [comment]
Happy to help :)
