### ISSUE TITLE
Spawned entities aren't replaced properly

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#61]
For BWR, Rocky needs to replace XPOrbs with a custom class, which works on world load, but not when newly spawned. `EntityList` has a method for replacing spawnable mappings, but it only looks at creatures. This method, `replaceSpawnableMappingSafe`, has reflection code and a comment stating it needs a rewrite.

https://github.com/BTW-Community/BTW-source/blob/9b6ba56eea798a97ddcdf92dc88b09be97341c24/minecraft/net/minecraft/src/EntityList.java#L349-L456

Is there a way to rewrite the method so it works for all spawnable entities?
Can we get around the fact that many different classes spawn XPOrb entities?
Should we refactor all entities to use an entity factory rather than constructors so that we can just handle it in that factory and skip the whole replacement thing?

I sorta prefer that last one, since it would fix this issue now and in the future for all addons and it's mostly fairly simple monkey code.

**Comment by ammoore00** [comment]
Entity factory and rplacement checking is live on entityFactory branch. Awaiting conversion of vanilla systems over to factory pattern.

Entities should have protected constructors to enforce design pattern while allowing children to call constructor.

**Comment by ammoore00** [comment]
Fixed for v1.1.0
