### ISSUE TITLE
Support modern player skins and models

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#7]
https://github.com/BTW-Community/BTW-source/issues/23#issuecomment-922570973
> A part of this should be moving the skin fix out of ThreadDownloadImage to a more sensible place.
> 
> Potentially rewriting to use Mojang's API, though that has a request limiter so may be more hassle than it is worth.

https://github.com/BTW-Community/BTW-source/issues/23

**Comment by ammoore00** [comment]
Move skin fix to a better place for v1.1.0.

Full modern skin support will come later.

**Comment by ammoore00** [comment]
Misclicked, didn't mean to close

**Comment by Hirachosan** [comment]
modern skin  and ear support added next release
