### ISSUE TITLE
Fire Enchantments are actively bad

### ISSUE THREAD

**Issue by SimonMeskens** [BTW-Community/BTW-Public#8]
They're the only bad enchant, but they don't force you to use it, so it's just a sword you'll throw in a chest for melting down. Either we add some sort of rogue style cursed items thing that you are forced to use, or we rework fire enchantments into something else like ice enchantments that slow down enemies instead.

Whuppee asked to retain the damage over time aspect, but don't have it set mobs on fire, which sounds like it would mean the wither effect instead.

https://github.com/BTW-Community/BTW-source/issues/34

**Comment by SimonMeskens** [comment]
Feedback thread: http://www.sargunster.com/btwforum/viewtopic.php?f=14&t=9898

**Comment by LannyRipple** [comment]
Fixed in CE-1.30, CE-1.32
